import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import styles from "../styles/Home.module.css";
import { FaArrowRight } from "react-icons/fa";
import { CiLocationOn } from "react-icons/ci";
import { kay } from "../public/BG";
import Link from "next/link";
import Header from "../components/Header";
import Favourites from "../components/Favourites";
export default function Home() {
  return (
    <>
      <Head>
        <title>Luugage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className={styles.getaway}>
          <Image src={kay} priority />
          <div className={styles.reasons}>
            <div className={styles.intro}>
              <p>
                365 NEW
                <br /> REASONS TO
                <br /> GET AWAY{" "}
              </p>
              <span>
                More travel. More curiosity. And with our luggage and bags—more
                <br /> room to pack it all in.
              </span>
              <button>SHOP NOW</button>
            </div>
          </div>
        </div>
        <div className={styles.highlight}>
          <p>
            A few of our <br />
            <span>FAVORITES.</span>
          </p>
        </div>
        <Favourites />
      </main>
    </>
  );
}

// const Container = styled.div`
//   .highlight {
//     display: flex;
//     justify-content: center;
//     align-items: center;
//     padding: 30px;
//     text-align: center;
//   }
//   .highlight span {
//     font-size: 60px;
//     font-family: "Times New Roman", Times, serif;
//     font-weight: 200;
//   }
//   .highlight p {
//     font-style: oblique;
//   }
//   .intro {
//     display: flex;
//     flex-direction: column;
//     justify-content: center;
//     align-items: center;
//     padding: 70px;
//     text-align: center;
//     gap: 20px;
//   }
//   .intro button {
//     background-color: black;
//     color: white;
//     border: none;
//     padding: 18px;
//     font-size: 18px;
//   }
//   .intro p {
//     font-size: var(--js-mobileFontSize);
//     font-size: 60px;
//     letter-spacing: 1px;
//   }
//   .intro span {
//     font-weight: 200;
//   }
//   .reasons {
//     background-color: #f7f0ea;
//     width: 100%;
//   }
//   .getaway img {
//     width: 100%;
//     height: 60%;
//   }
//   .getaway {
//     display: flex;
//     padding-top: 100px;
//   }
// `;
